CREATE DATABASE IF NOT EXISTS trackgenda;

USE trackgenda;

CREATE TABLE IF NOT EXISTS user_info (
    uid INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    u_email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    u_password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS monthly_event (
	meventid INT AUTO_INCREMENT PRIMARY KEY,
	uid INT NOT NULL,
	mevent_date VARCHAR(255) NOT NULL,
	mevent_desc VARCHAR(255) NOT NULL,
	CONSTRAINT FK_MEVENT_UID FOREIGN KEY (uid) REFERENCES user_info(uid)
)
